version: 1.0.{build}
branches:
  only:
  - master
max_jobs: 1
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a Sistema_TCS.zip TCS\bin\Debug\*.*
artifacts:
- path: Sistema_TCS.zip
  name: Sistema_TCS
services:
  - mysql
deploy:
- provider: Environment
  name: G4 Pruebas
  artifact : Sistema_TCS
after_deploy:
- cmd: MySQLSetup.bat