version: 1.0.{build}
branches:
  only:
  - master
max_jobs: 1
build:
  verbosity: minimal
after_build:
- cmd: 7z a Sistema_TCS.zip TCS\bin\Debug\*.*
artifacts:
- path: Sistema_TCS.zip
  name: Sistema_TCS
deploy:
- provider: Environment
  name: G4 Pruebas
  artifact : Sistema_TCS
after_deploy:
- cmd: '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -u root -p12345678 < "C:\appveyor\projects\2017-ii-1394-igii-g4\applications\Sistema_TCS\TCS\bin\Debug\TCS_DB.sql"'