//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseModelContainer : DbContext
    {
        public DatabaseModelContainer()
            : base("name=DatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flota> flotas { get; set; }
        public virtual DbSet<flotaunidad> flotaunidads { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<personarol> personarols { get; set; }
        public virtual DbSet<punto> puntoes { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<ruta> rutas { get; set; }
        public virtual DbSet<rutapunto> rutapuntoes { get; set; }
        public virtual DbSet<unidad> unidads { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<viaje> viajes { get; set; }
    }
}
