//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class flotaunidad
    {
        public int FlotaUnidadID { get; set; }
        public Nullable<int> FlotaID { get; set; }
        public Nullable<int> UnidadID { get; set; }
    
        public virtual flota flota { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
