//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class flotaunidad
    {
        public int FlotaUnidadID { get; set; }
        public Nullable<int> FlotaID { get; set; }
        public Nullable<int> UnidadID { get; set; }
    
        public virtual flota flota { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
