//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaHorario
    {
        public int PersonaHorarioID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> HorarioID { get; set; }
    }
}
