//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class personarol
    {
        public int PersonaRol1 { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> RolID { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual rol rol { get; set; }
    }
}
