//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaHorario
    {
        public int PersonaHorarioID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> HorarioID { get; set; }
    }
}
