//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutapunto
    {
        public int RutaPuntoID { get; set; }
        public Nullable<int> RutaID { get; set; }
        public Nullable<int> PuntoID { get; set; }
    
        public virtual ruta ruta { get; set; }
    }
}
