//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCS_Entities : DbContext
    {
        public TCS_Entities()
            : base("name=TCS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flota> flota { get; set; }
        public virtual DbSet<flotaunidad> flotaunidad { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<personarol> personarol { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<punto> punto { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<rutapunto> rutapunto { get; set; }
        public virtual DbSet<unidad> unidad { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<viaje> viaje { get; set; }
    }
}
