//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        public int ViajeID { get; set; }
        public Nullable<int> UnidadID { get; set; }
        public Nullable<int> RutaID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<System.DateTime> FechaPartida { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
        public string Descripcion { get; set; }
        public string Orden { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual unidad unidad { get; set; }
        public virtual ruta ruta { get; set; }
    }
}
