//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tcsdbEntities : DbContext
    {
        public tcsdbEntities()
            : base("name=tcsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flota> flota { get; set; }
        public virtual DbSet<flotaunidad> flotaunidad { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<personarol> personarol { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<punto> punto { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<rutapunto> rutapunto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unidad> unidad { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<viaje> viaje { get; set; }
    }
}
